### ISSUE TITLE
Shortcode is not interpreted by grav

### ISSUE THREAD

**Issue by xieciun** [deved-it/grav-plugin-google-maps#2]
I am quite fresh Grav user and I am struggling with using your plugin.

I have instlled fresh grav with admin plugin (no extras) and added three plugins to check it:

Google maps (added via admin panel)
Shordcode core (added as depenency gy grav admin panel)
Shortcode UI (added via admin panel)

Shortcodes from Shortcode UI are working fine, but shortcode from Google maps doesn't work (Google API key is added).

You may see how it looks like on this page:
http://choinki2.twojedecyzje.pl/

Any suggestion is welcome, maybe I am doing something wrong.

**Comment by salgua** [comment]
Hi @xieciun!
thanks for reaching out! The plugin was working with previous version of Grav and Shortcode plugins, it seems now something is broken. Give me some days to investigate. I'll back to you soon.

**Comment by le717** [comment]
I too am experiencing this issue. Even if I copy your example from the readme, this is all the markup I get in my browser.

``` html
<div id="map-e98bb7766c" class="google-map" style="width: 100%; height: 400px" data-lat="44.540" data-lng="-78.546" data-zoom="13" data-infowindow="
<p><strong><em>My Place</em></strong><br />
This is my place  </p>
">
</div>
```

**Comment by xieciun** [comment]
Hi,
looks like there is another way to get google maps in grav

http://diblas.net/plugins/use-bootstrap-components-as-shortcodes-in-grav-cms/gravstrap-google-map-shortcode

BR
Arek

**Comment by isthisthat** [comment]
Haven't had luck with any of these either. Same issue with folks above.

**Comment by salgua** [comment]
I just pushed v.1.0.4. I did some tests using a fresh installation of the last stable release of grav. It works fine using antimatter theme and other themes like bones. Could you verify again and give me some feedback?

**Comment by endomorphismus** [comment]
Unfortunately it still does not work (does not render), just installed fresh Grav+Antimatter+GmapsAPI Key. Using this example it just renders the markup on the page
[google-maps width='100%' lat=44.540 lng=-78.546 zoom=13]
**_My Place**_  
This is my place  
[/google-maps]

**Comment by salgua** [comment]
@endomorphismus thank you for your feedback! How did you install the plugin? Using bin/gpm? Could you share your installation?

**Comment by endomorphismus** [comment]
@salgua i've installed it via bin/gpm and also tried it via Admin. Had issues with both. What exactly do you need from my install?

**Comment by salgua** [comment]
@endomorphismus everything, your fresh install + installed plugins + your test page. You can share a zip file through dropbox, goggle drive etc.

**Comment by salgua** [comment]
Hi @endomorphismus, I took a look to your install. It's not a fresh install, you have 30 plugins :) however I found the problem: you used the shortcode in a modular page. The shortcode is correctly interpreted but the google-maps js is not present in the page. There is a bug with modular page.

**Comment by salgua** [comment]
Just opened [new bug](https://github.com/deved-it/grav-plugin-google-maps/issues/4)
